// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by `sip run barrel`

export 'src/data/news_templates.dart';
export 'src/data/news_vocabulary.dart';
export 'src/generators/news_generator.dart';
export 'src/repos/news_headline_repo.dart';
export 'src/repos/sector_stats_repo.dart';
export 'src/setup/setup.config.dart';
export 'src/setup/setup.dart';
