name: suppressed_intelligence
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

workspace:
  # ignore: path_does_not_exist
  - packages/*

dependencies:
  flutter:
    sdk: flutter
  ui:
    path: packages/ui
  application:
    path: packages/application
  data:
    path: packages/data

  flame: ^1.35.1
  equatable: ^2.0.8
  get_it: ^9.2.1
  scoped_deps: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  equatable_gen: ^1.3.1
  build_runner: ^2.12.2
  flame_lint: ^1.4.2
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

scripts: derry.yaml
