name: ui
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  animated_text_kit: ^4.3.0
  application:
    path: ../application
  domain:
    path: ../domain
  flame: ^1.34.0
  flame_audio: ^2.12.0
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  universal_html: ^2.3.0
  zenrouter: ^0.4.16
